server:
  rootPath: /app/
  applicationConnectors:
    - type: http
      port: 8095
  adminConnectors:
    - type: http
      port: 8096

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: mysecretpassword
  url: jdbc:postgresql://localhost:5432/expensedb
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* ExpenseService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute